const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const STATE='saborcaseiro_marmita', CART='saborcaseiro_cart';
const getState=()=>JSON.parse(localStorage.getItem(STATE)||'{}');
const setState=v=>localStorage.setItem(STATE,JSON.stringify(v));
const getCart=()=>JSON.parse(localStorage.getItem(CART)||'[]');
const setCart=v=>{localStorage.setItem(CART,JSON.stringify(v));badge()};
function toast(msg,err=false){const x=document.createElement('div');x.textContent=msg;x.style.cssText=`position:fixed;right:22px;bottom:22px;z-index:99999;padding:14px 18px;border-radius:12px;background:${err?'#a51f1f':'#245c39'};color:white;font:600 14px Poppins,sans-serif;box-shadow:0 10px 25px #0003`;document.body.append(x);setTimeout(()=>x.remove(),3500)}
function badge(){$$('.cart-badge').forEach(x=>x.textContent=getCart().length)}
async function profile(){const {data:{user}}=await db.auth.getUser();if(!user)return null;const {data}=await db.from('usuarios').select('*').eq('id',user.id).maybeSingle();return data}
async function authHeader(){const {data:{user}}=await db.auth.getUser();const links=$$('header a.nav-link-custom');if(!user)return;const p=await profile();links.filter(a=>['Entrar','Cadastrar'].includes(a.textContent.trim())).forEach(a=>a.remove());const host=$('header .d-flex.align-items-center.gap-3.gap-md-4')||$('header .d-flex.align-items-center.gap-3');if(host){if(p?.tipo==='Administrador'){const a=document.createElement('a');a.href='administrador.php';a.className='nav-link-custom';a.textContent='Painel ADM';host.append(a)}const out=document.createElement('button');out.className='nav-link-custom';out.style.cssText='border:0;background:transparent';out.textContent='Sair';out.onclick=async()=>{await db.auth.signOut();location.href='index.php'};host.append(out)}}
async function home(){if(!location.pathname.endsWith('index.php')&&!location.pathname.endsWith('/'))return;const {data:cfg}=await db.from('configuracoes_loja').select('*').limit(1).maybeSingle();if(cfg){const sub=$('.hero-subtitle');if(sub&&cfg.descricao)sub.textContent=cfg.descricao;const nome=cfg.nome_loja||'Sabor Caseiro';const setText=(sel,val)=>{const el=$(sel);if(el&&val)el.textContent=val};setText('#footer-store-name',nome);setText('#footer-store-name-bottom',nome);setText('#footer-store-description',cfg.descricao);const phoneDigits=String(cfg.telefone||'').replace(/\D/g,'');const phone=$('#footer-phone');if(phone&&cfg.telefone){phone.classList.remove('d-none');$('span',phone).textContent=cfg.telefone;phone.href='tel:'+phoneDigits}const addr=$('#footer-address');if(addr&&cfg.endereco){addr.classList.remove('d-none');$('span',addr).textContent=cfg.endereco;addr.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(cfg.endereco)}const insta=$('#footer-instagram');if(insta&&cfg.instagram){const handle=String(cfg.instagram).trim().replace(/^@/,'').replace(/^https?:\/\/(www\.)?instagram\.com\//i,'').replace(/\/.*$/,'');if(handle){insta.classList.remove('d-none');$('span',insta).textContent='@'+handle;insta.href='https://www.instagram.com/'+encodeURIComponent(handle)+'/';}}const wa=$('#floating-whatsapp');if(wa&&cfg.whatsapp){const waDigits=String(cfg.whatsapp).replace(/\D/g,'');if(waDigits){wa.classList.remove('d-none');wa.href='https://wa.me/'+waDigits;}}}const fy=$('#footer-year');if(fy)fy.textContent=String(new Date().getFullYear());const {data:m,error}=await db.from('marmitas_do_dia').select('*,tamanhos_marmita(*),marmitas_do_dia_ingredientes(ingrediente_id,ingredientes(*))').eq('publicada',true).eq('disponivel',true).limit(1).maybeSingle();const card=$('.menu-card');if(error){console.error('Erro ao carregar marmita do dia:',error);return}if(!m){card?.classList.add('d-none');return}const nome=$('.menu-card-dish'),desc=$('.menu-card-desc'),img=$('.menu-card-img'),tam=$('.menu-card-size'),preco=$('.menu-card-price'),btn=$('#add-marmita-dia');const comps=(m.marmitas_do_dia_ingredientes||[]).map(x=>x.ingredientes).filter(Boolean);if(nome)nome.textContent=m.nome;if(desc)desc.textContent=m.descricao||comps.map(x=>x.nome).join(', ');if(img){img.src=m.imagem_url||'https://placehold.co/600x400/png?text=Marmita+do+Dia';img.alt=m.nome}if(tam)tam.textContent=m.tamanhos_marmita?.nome||'';const calc=Number(m.tamanhos_marmita?.preco||0)+comps.reduce((a,x)=>a+Number(x.preco_adicional||0),0);const valor=m.preco_promocional==null?calc:Number(m.preco_promocional);if(preco)preco.textContent=money(valor);if(btn)btn.onclick=()=>{const c=getCart();c.push({tamanho:m.tamanhos_marmita,ingredientes:comps,nome:m.nome,preco_fixo:valor,marmita_dia_id:m.id});setCart(c);badge();toast('Marmita do dia adicionada ao carrinho!')}}
function passwordEyes(){$$('.password-toggle').forEach(i=>i.onclick=()=>{const inp=i.previousElementSibling;if(!inp)return;inp.type=inp.type==='password'?'text':'password';i.classList.toggle('bi-eye');i.classList.toggle('bi-eye-slash')})}
async function cadastro(){if(!location.pathname.endsWith('cadastro.php'))return;const f=$('form');if(!f)return;f.onsubmit=async e=>{e.preventDefault();if($('#senha').value!==$('#confirmarSenha').value)return toast('As senhas não coincidem.',true);const {data,error}=await db.auth.signUp({email:$('#email').value.trim(),password:$('#senha').value,options:{data:{nome:$('#nome').value.trim(),telefone:$('#telefone').value.trim()}}});if(error)return toast(error.message,true);if(data.user&&$('#endereco').value.trim())await db.from('usuarios').update({endereco:$('#endereco').value.trim()}).eq('id',data.user.id);toast('Conta criada! Verifique seu e-mail se a confirmação estiver ativada.');setTimeout(()=>location.href='login.php',1300)}}
function ensureLoginDesign(){if(!location.pathname.endsWith('login.php'))return;const main=$('main');if(!main)return;main.className='signup-wrap d-flex align-items-center justify-content-center py-5';main.innerHTML=`<div class="signup-form-inner"><div class="d-flex align-items-center justify-content-center gap-2 mb-3"><img src="./img/logoooo.png" alt="Sabor Caseiro" class="logo-img-card"><span class="brand-name fs-5">Sabor Caseiro</span></div><div class="text-center mb-4"><h2 class="signup-title">Entre na sua conta</h2><p class="signup-subtitle m-0">Acesse seus pedidos e continue montando sua marmita</p></div><form id="login-form"><div class="mb-3"><label for="email" class="form-label-custom">Email</label><input type="email" class="form-control form-control-custom" id="email" placeholder="seu@email.com" required></div><div class="mb-2"><label for="senha" class="form-label-custom">Senha</label><div class="password-wrap"><input type="password" class="form-control form-control-custom" id="senha" placeholder="••••••••" required><i class="bi bi-eye-slash password-toggle"></i></div></div><div class="text-end mb-4"><a href="recuperar-senha.php" class="login-link">Esqueci minha senha</a></div><button type="submit" class="btn btn-cta w-100">Entrar</button><p class="login-link mt-3">Ainda não tem conta? <a href="cadastro.php">Cadastre-se</a></p></form></div>`;passwordEyes()}
async function login(){if(!location.pathname.endsWith('login.php'))return;const f=$('#login-form');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const {data,error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#senha').value});if(error)return toast('E-mail ou senha incorretos.',true);const {data:p}=await db.from('usuarios').select('tipo').eq('id',data.user.id).single();location.href=p?.tipo==='Administrador'?'administrador.php':'index.php'}}
function total(){const s=getState();return Number(s.tamanho?.preco||0)+(s.ingredientes||[]).reduce((a,x)=>a+Number(x.preco_adicional||0),0)}
function showTotal(){const e=$('.summary-total strong');if(e)e.textContent=money(total())}
async function montarMarmita(){
 if(!location.pathname.endsWith('montarmarmita.php'))return;
 const options=$('#marmita-options'),stepsEl=$('#marmita-steps'),title=$('#marmita-stage-title'),help=$('#marmita-stage-help'),limit=$('#marmita-limit'),back=$('#marmita-back'),next=$('#marmita-next');
 if(!options||!stepsEl)return;
 let st=getState(),etapa=0,tamanhosData=[],ingredientesData=[];
 const defs=[{key:'tamanho',label:'Tamanho'},{key:'Proteína',label:'Proteína',max:'max_proteinas'},{key:'Carboidrato',label:'Carboidrato',max:'max_carboidratos'},{key:'Acompanhamento',label:'Acompanhamento',max:'max_acompanhamentos'},{key:'Salada',label:'Salada',max:'max_saladas'}];
 const {data:ts,error:te}=await db.from('tamanhos_marmita').select('*').eq('disponivel',true).order('ordem');
 if(te){options.innerHTML='<div class="col-12"><p>Erro ao carregar tamanhos.</p></div>';return console.error(te)}
 tamanhosData=ts||[];
 const {data:ings,error:ie}=await db.from('ingredientes').select('*').eq('disponivel',true).order('ordem');
 if(ie){options.innerHTML='<div class="col-12"><p>Erro ao carregar ingredientes.</p></div>';return console.error(ie)}
 ingredientesData=ings||[];
 function etapas(){return defs.filter((d,i)=>i===0||Number(st.tamanho?.[d.max]||0)>0)}
 function selecionados(cat){return(st.ingredientes||[]).filter(x=>x.categoria===cat)}
 function renderSteps(){const es=etapas();stepsEl.innerHTML=es.map((x,i)=>`<div class="builder-step ${i<etapa?'done':i===etapa?'active':''}"><span>${i<etapa?'<i class="bi bi-check-lg"></i>':i+1}</span><small>${x.label}</small></div>`).join('')}
 function cardIngrediente(x,selected){return `<div class="col-12 col-md-6 col-xl-4"><button type="button" class="btn btn-marmita-proteina builder-option w-100 d-flex align-items-center p-3 text-start ${selected?'active':''}" data-id="${x.id}">${x.imagem_url?`<div class="img-container me-3 bg-light overflow-hidden"><img src="${x.imagem_url}" alt="${x.nome}"></div>`:'<div class="img-container me-3 bg-light overflow-hidden d-flex align-items-center justify-content-center"><i class="bi bi-egg-fried fs-2 text-dark"></i></div>'}<div class="text-white overflow-hidden flex-grow-1"><strong class="d-block fs-5 mb-1 text-truncate">${x.nome}</strong><span class="d-block small text-light text-truncate opacity-75">${x.descricao||x.categoria}${Number(x.preco_adicional)>0?' • +'+money(x.preco_adicional):''}</span></div><i class="bi bi-check-circle-fill builder-check ms-2"></i></button></div>`}
 function render(){st=getState();const es=etapas();if(etapa>=es.length)etapa=es.length-1;const d=es[etapa];renderSteps();back.disabled=etapa===0;next.innerHTML=etapa===es.length-1?'Adicionar ao carrinho <i class="bi bi-cart-plus"></i>':'Continuar <i class="bi bi-arrow-right"></i>';limit.classList.add('d-none');
  if(etapa===0){title.textContent='Escolha o tamanho da sua marmita';help.textContent='O tamanho define o preço base e quantos itens você pode escolher.';options.innerHTML=tamanhosData.map(x=>`<div class="col-12 col-md-4"><button type="button" class="btn btn-marmita builder-option w-100 ${String(st.tamanho?.id)===String(x.id)?'active':''}" data-id="${x.id}"><strong>${x.nome}</strong><strong>${money(x.preco)}</strong>${x.descricao?`<span>${x.descricao}</span>`:''}<span>• até ${x.max_carboidratos} carboidrato(s)</span><span>• até ${x.max_proteinas} proteína(s)</span><span>• até ${x.max_acompanhamentos} acompanhamento(s)</span>${Number(x.max_saladas)>0?`<span>• até ${x.max_saladas} salada(s)</span>`:''}</button></div>`).join('')||'<div class="col-12"><p>Nenhum tamanho disponível.</p></div>';$$('.builder-option',options).forEach(b=>b.onclick=()=>{const x=tamanhosData.find(v=>String(v.id)===b.dataset.id);const mudou=String(st.tamanho?.id)!==String(x.id);setState({tamanho:x,ingredientes:mudou?[]:(st.ingredientes||[])});render();showTotal()})}
  else{const cat=d.key,max=Number(st.tamanho?.[d.max]||0),sel=selecionados(cat),data=ingredientesData.filter(x=>x.categoria===cat);title.textContent=`Escolha ${d.label.toLowerCase()}`;help.textContent='Toque em uma opção para selecionar ou remover.';limit.textContent=`${sel.length} de ${max} selecionado(s)`;limit.classList.remove('d-none');options.innerHTML=data.map(x=>cardIngrediente(x,sel.some(v=>String(v.id)===String(x.id)))).join('')||`<div class="col-12"><div class="alert alert-light border">Nenhuma opção de ${d.label.toLowerCase()} disponível.</div></div>`;$$('.builder-option',options).forEach(b=>b.onclick=()=>{const x=data.find(v=>String(v.id)===b.dataset.id);let atual=selecionados(cat);if(atual.some(v=>String(v.id)===String(x.id)))atual=atual.filter(v=>String(v.id)!==String(x.id));else{if(atual.length>=max)return toast(`Escolha no máximo ${max}.`,true);atual.push(x)}setState({...getState(),ingredientes:[...(getState().ingredientes||[]).filter(v=>v.categoria!==cat),...atual]});render();showTotal()})}
  showTotal();
 }
 back.onclick=()=>{if(etapa>0){etapa--;render()}};
 next.onclick=()=>{st=getState();const es=etapas(),d=es[etapa];if(etapa===0&&!st.tamanho)return toast('Escolha o tamanho da marmita.',true);if(etapa>0&&selecionados(d.key).length===0)return toast(`Escolha pelo menos uma opção de ${d.label.toLowerCase()}.`,true);if(etapa<es.length-1){etapa++;render();return}const c=getCart();c.push(getState());setCart(c);localStorage.removeItem(STATE);toast('Marmita adicionada ao carrinho!');setTimeout(()=>location.href='carrinho.php',500)};
 render();
}
async function carrinho(){if(!location.pathname.endsWith('carrinho.php'))return;const main=$('.cart-section .container'), items=getCart();if(!main)return;if(!items.length)return;main.innerHTML=`<h2 class="cart-empty-title text-center mb-4">Seu carrinho</h2><div class="cart-items">${items.map((x,i)=>`<div class="cart-item d-flex justify-content-between align-items-center mb-3"><div><strong>${x.nome||x.tamanho.nome}</strong><p class="mb-0">${(x.ingredientes||[]).map(y=>y.nome).join(', ')}</p></div><div class="d-flex align-items-center gap-3"><strong>${money(x.preco_fixo??(Number(x.tamanho.preco)+(x.ingredientes||[]).reduce((a,y)=>a+Number(y.preco_adicional||0),0)))}</strong><button class="btn btn-sm btn-outline-danger remove-cart" data-i="${i}"><i class="bi bi-trash"></i></button></div></div>`).join('')}</div><div class="d-flex justify-content-between align-items-center mt-4"><strong>Total: ${money(items.reduce((a,x)=>a+Number(x.preco_fixo??(Number(x.tamanho.preco)+(x.ingredientes||[]).reduce((b,y)=>b+Number(y.preco_adicional||0),0))),0))}</strong><button id="checkout" class="btn btn-cta">Finalizar pedido</button></div>`;$$('.remove-cart').forEach(b=>b.onclick=()=>{const c=getCart();c.splice(+b.dataset.i,1);setCart(c);carrinho()});$('#checkout').onclick=checkout}
async function api(url,opt={}){const {data:{session}}=await db.auth.getSession();const headers={'Content-Type':'application/json',...(opt.headers||{})};if(session?.access_token)headers.Authorization='Bearer '+session.access_token;const r=await fetch(url,{...opt,headers});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Erro no servidor.');return j}
async function checkout(){const {data:{user}}=await db.auth.getUser();if(!user)return toast('Entre na sua conta para finalizar.',true),setTimeout(()=>location.href='login.php',1000);const c=getCart();try{const j=await api('api/checkout.php',{method:'POST',body:JSON.stringify({usuario_id:user.id,itens:c.map(x=>({tamanho_id:x.tamanho.id,ingrediente_ids:(x.ingredientes||[]).map(y=>y.id),marmita_dia_id:x.marmita_dia_id||null}))})});setCart([]);toast(`Pedido #${j.pedido.id} realizado!`);setTimeout(()=>location.href='index.php',1200)}catch(e){toast(e.message,true)}}
async function admin(){
 if(!location.pathname.endsWith('administrador.php'))return;
 const p=await profile();if(!p||p.tipo!=='Administrador')return location.href='login.php';
 const name=$('.admin-user span');if(name)name.textContent=p.nome||'Administrador';
 const go=id=>{$$('.sidebar-item').forEach(x=>x.classList.toggle('active',x.dataset.section===id));$$('.admin-section').forEach(x=>x.classList.toggle('active-section',x.id===id))};
 $$('.sidebar-item').forEach(x=>x.onclick=()=>go(x.dataset.section));$$('[data-go-section]').forEach(x=>x.onclick=()=>go(x.dataset.goSection));
 $('#logout-btn')?.addEventListener('click',async()=>{await db.auth.signOut();location.href='login.php'});
 try{
  const d=await api('api/admin.php?recurso=dashboard');
  $('#dash-faturamento').textContent=money(d.faturamento_hoje);$('#dash-pedidos').textContent=d.pedidos_hoje;$('#dash-pedidos-info').textContent=`${d.em_preparo} em preparo`;$('#dash-marmitas').textContent=d.marmitas_vendidas;$('#dash-clientes').textContent=d.clientes;
  const recent=$('#dashboard-pedidos-recentes');if(recent)recent.innerHTML=(d.pedidos_recentes||[]).length?d.pedidos_recentes.map(o=>`<tr><td><strong>#${o.id}</strong></td><td>${o.usuarios?.nome||'Cliente'}</td><td>${money(o.valor_total)}</td><td><span class="status">${o.status}</span></td></tr>`).join(''):'<tr><td colspan="4">Nenhum pedido hoje.</td></tr>';
  const resumo=$('#dashboard-cardapio-resumo');if(resumo)resumo.innerHTML=(d.tamanhos||[]).map(x=>`<div class="product-row"><div class="product-icon"><i class="bi bi-egg-fried"></i></div><div><strong>${x.nome}</strong><span>${money(x.preco)}</span></div><span class="available">${x.disponivel?'Ativo':'Inativo'}</span></div>`).join('')||'<p class="mb-0">Nenhum tamanho cadastrado.</p>';
 }catch(e){toast('Não foi possível atualizar o dashboard: '+e.message,true)}
 try{
  const orders=await api('api/admin.php?recurso=pedidos');
  const badgeAdm=$('#pedidos-badge');if(badgeAdm)badgeAdm.textContent=orders.filter(o=>!['Entregue','Cancelado'].includes(o.status)).length;
  const sec=$('#pedidos');if(sec){const tb=$('tbody',sec);if(tb)tb.innerHTML=orders.length?orders.map(o=>`<tr><td>#${o.id}</td><td>${o.usuarios?.nome||'Cliente'}</td><td>${money(o.valor_total)}</td><td><select class="form-select form-select-sm adm-status" data-id="${o.id}">${['Pendente','Em Preparo','Saiu para Entrega','Entregue','Cancelado'].map(st=>`<option ${st===o.status?'selected':''}>${st}</option>`).join('')}</select></td></tr>`).join(''):'<tr><td colspan="4">Nenhum pedido.</td></tr>'}
  $$('.adm-status').forEach(el=>el.onchange=async()=>{try{await api('api/admin.php?recurso=status&id='+el.dataset.id,{method:'PATCH',body:JSON.stringify({status:el.value})});toast('Status atualizado.')}catch(e){toast(e.message,true)}});

  const tamanhos=await api('api/admin.php?recurso=tamanhos'), gridT=$('#grid-tamanhos');
  if(gridT)gridT.innerHTML=tamanhos.length?tamanhos.map(x=>`<div class="col-xl-4 col-md-6"><div class="menu-admin-card"><div class="menu-admin-image">${x.imagem_url?`<img src="${x.imagem_url}" alt="${x.nome}">`:'<i class="bi bi-box2-heart"></i>'}</div><div class="menu-admin-info"><div class="d-flex justify-content-between"><h3>${x.nome}</h3><span class="available">${x.disponivel?'Ativo':'Inativo'}</span></div><p>${x.descricao||`Limites: ${x.max_carboidratos} carb., ${x.max_proteinas} prot., ${x.max_acompanhamentos} acomp., ${x.max_saladas} salada(s)`}</p><strong>${money(x.preco)}</strong><div class="menu-actions"><button class="btn-outline-custom edit-tam" data-id="${x.id}"><i class="bi bi-pencil"></i> Editar</button><button class="delete-btn del-tam" data-id="${x.id}"><i class="bi bi-trash"></i></button></div></div></div></div>`).join(''):'<div class="col-12"><p>Nenhum tamanho cadastrado.</p></div>';
  const modalTEl=$('#modalTamanho'),modalT=modalTEl?new bootstrap.Modal(modalTEl):null;
  const abrirT=(x=null)=>{$('#tamanho-id').value=x?.id||'';$('#tamanho-nome').value=x?.nome||'';$('#tamanho-preco').value=x?.preco||0;$('#tamanho-descricao').value=x?.descricao||'';$('#tamanho-carb').value=x?.max_carboidratos??1;$('#tamanho-prot').value=x?.max_proteinas??1;$('#tamanho-acomp').value=x?.max_acompanhamentos??1;$('#tamanho-salada').value=x?.max_saladas??0;$('#tamanho-ordem').value=x?.ordem??0;$('#tamanho-disponivel').checked=x?.disponivel??true;$('#tituloModalTamanho').textContent=x?'Editar tamanho':'Novo tamanho';modalT?.show()};
  $('#novo-tamanho')?.addEventListener('click',()=>abrirT());$$('.edit-tam').forEach(b=>b.onclick=()=>abrirT(tamanhos.find(x=>String(x.id)===b.dataset.id)));$$('.del-tam').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este tamanho? Pedidos históricos podem impedir a exclusão.'))return;try{await api('api/admin.php?recurso=tamanho&id='+b.dataset.id,{method:'DELETE'});toast('Tamanho excluído.');setTimeout(()=>location.reload(),400)}catch(e){toast(e.message,true)}});
  $('#formTamanho')?.addEventListener('submit',async e=>{e.preventDefault();const id=$('#tamanho-id').value,dados={nome:$('#tamanho-nome').value.trim(),preco:Number($('#tamanho-preco').value),descricao:$('#tamanho-descricao').value.trim(),max_carboidratos:Number($('#tamanho-carb').value),max_proteinas:Number($('#tamanho-prot').value),max_acompanhamentos:Number($('#tamanho-acomp').value),max_saladas:Number($('#tamanho-salada').value),ordem:Number($('#tamanho-ordem').value||0),disponivel:$('#tamanho-disponivel').checked};try{await api('api/admin.php?recurso=tamanho'+(id?'&id='+id:''),{method:id?'PATCH':'POST',body:JSON.stringify(dados)});toast('Tamanho salvo.');modalT?.hide();setTimeout(()=>location.reload(),400)}catch(e){toast(e.message,true)}});

  const ings=await api('api/admin.php?recurso=ingredientes'),gridI=$('#grid-ingredientes');
  if(gridI)gridI.innerHTML=ings.length?ings.map(x=>`<div class="col-xl-4 col-md-6"><div class="menu-admin-card"><div class="menu-admin-image">${x.imagem_url?`<img src="${x.imagem_url}" alt="${x.nome}">`:'<i class="bi bi-egg-fried"></i>'}</div><div class="menu-admin-info"><div class="d-flex justify-content-between"><h3>${x.nome}</h3><span class="available">${x.disponivel?'Ativo':'Inativo'}</span></div><p>${x.descricao||x.categoria}</p><strong>${Number(x.preco_adicional)>0?'+ '+money(x.preco_adicional):'Sem adicional'}</strong><div class="menu-actions"><button class="btn-outline-custom edit-ing" data-id="${x.id}"><i class="bi bi-pencil"></i> Editar</button><button class="delete-btn del-ing" data-id="${x.id}"><i class="bi bi-trash"></i></button></div></div></div></div>`).join(''):'<div class="col-12"><p>Nenhum ingrediente cadastrado.</p></div>';
  const modalEl=$('#modalIngrediente'),modalIngrediente=modalEl?new bootstrap.Modal(modalEl):null;let imagemAtual='',removerImagem=false;
  const preview=url=>{const w=$('#ingrediente-imagem-preview-wrap'),im=$('#ingrediente-imagem-preview');if(!w||!im)return;if(url){im.src=url;w.classList.remove('d-none')}else{im.removeAttribute('src');w.classList.add('d-none')}};
  const abrirI=(x=null)=>{$('#ingrediente-id').value=x?.id||'';$('#ingrediente-nome').value=x?.nome||'';$('#ingrediente-descricao').value=x?.descricao||'';$('#ingrediente-preco').value=x?.preco_adicional||0;$('#ingrediente-categoria').value=x?.categoria||'Carboidrato';$('#ingrediente-disponivel').checked=x?.disponivel??true;$('#ingrediente-imagem').value='';imagemAtual=x?.imagem_url||'';removerImagem=false;preview(imagemAtual);$('#tituloModalIngrediente').textContent=x?'Editar ingrediente':'Novo ingrediente';modalIngrediente?.show()};
  $('#novo-ingrediente')?.addEventListener('click',()=>abrirI());$$('.edit-ing').forEach(b=>b.onclick=()=>abrirI(ings.find(x=>String(x.id)===b.dataset.id)));$$('.del-ing').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este ingrediente?'))return;try{await api('api/admin.php?recurso=ingrediente&id='+b.dataset.id,{method:'DELETE'});toast('Ingrediente excluído.');setTimeout(()=>location.reload(),400)}catch(e){toast(e.message,true)}});
  $('#ingrediente-imagem')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return preview(imagemAtual);if(!['image/jpeg','image/png','image/webp'].includes(f.type)){e.target.value='';return toast('Use JPG, PNG ou WebP.',true)}if(f.size>5*1024*1024){e.target.value='';return toast('A imagem deve ter no máximo 5 MB.',true)}removerImagem=false;preview(URL.createObjectURL(f))});$('#remover-imagem')?.addEventListener('click',()=>{$('#ingrediente-imagem').value='';removerImagem=true;preview('')});
  $('#formIngrediente')?.addEventListener('submit',async e=>{e.preventDefault();const id=$('#ingrediente-id').value,dados={nome:$('#ingrediente-nome').value.trim(),categoria:$('#ingrediente-categoria').value,descricao:$('#ingrediente-descricao').value.trim(),preco_adicional:Number($('#ingrediente-preco').value||0),disponivel:$('#ingrediente-disponivel').checked};try{const arquivo=$('#ingrediente-imagem').files?.[0];if(arquivo){const {data:{user}}=await db.auth.getUser();if(!user)throw new Error('Sessão expirada.');const ext=(arquivo.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`ingredientes/${user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('produtos').upload(path,arquivo,{contentType:arquivo.type,upsert:false});if(error)throw error;dados.imagem_url=db.storage.from('produtos').getPublicUrl(path).data.publicUrl}else if(removerImagem)dados.imagem_url=null;await api('api/admin.php?recurso=ingrediente'+(id?'&id='+id:''),{method:id?'PATCH':'POST',body:JSON.stringify(dados)});toast('Ingrediente salvo.');modalIngrediente?.hide();setTimeout(()=>location.reload(),400)}catch(e){toast(e.message||'Erro ao salvar ingrediente.',true)}});

  const users=await api('api/admin.php?recurso=clientes_resumo'),ct=$('#clientes-tbody');if(ct)ct.innerHTML=users.length?users.map(u=>`<tr><td><strong>${u.nome}</strong><br><small>${u.email}</small></td><td>${u.telefone||'-'}</td><td>${u.pedidos}</td><td>${money(u.total_gasto)}</td><td><button class="table-action" title="${u.email}"><i class="bi bi-person"></i></button></td></tr>`).join(''):'<tr><td colspan="5">Nenhum cliente cadastrado.</td></tr>';

  const cfg=await api('api/admin.php?recurso=configuracoes');if(cfg){$('#cfg-nome').value=cfg.nome_loja||'';$('#cfg-instagram').value=cfg.instagram||'';$('#cfg-descricao').value=cfg.descricao||'';$('#cfg-telefone').value=cfg.telefone||'';$('#cfg-whatsapp').value=cfg.whatsapp||'';$('#cfg-endereco').value=cfg.endereco||'';$('#cfg-taxa').value=cfg.taxa_entrega??0;$('#cfg-minimo').value=cfg.pedido_minimo??0;$('#cfg-tempo-min').value=cfg.tempo_entrega_min??30;$('#cfg-tempo-max').value=cfg.tempo_entrega_max??60;$('#cfg-aberto').checked=!!cfg.aberto;$('#cfg-mensagem').value=cfg.mensagem_fechado||'';const rs=$('#restaurant-status');if(rs){$('strong',rs).textContent=cfg.aberto?'Marmitaria aberta':'Marmitaria fechada';$('small',rs).textContent=cfg.aberto?'Recebendo pedidos':(cfg.mensagem_fechado||'Não recebendo pedidos')}}
  $('#form-configuracoes')?.addEventListener('submit',async e=>{e.preventDefault();const dados={nome_loja:$('#cfg-nome').value.trim(),instagram:$('#cfg-instagram').value.trim(),descricao:$('#cfg-descricao').value.trim(),telefone:$('#cfg-telefone').value.trim(),whatsapp:$('#cfg-whatsapp').value.trim(),endereco:$('#cfg-endereco').value.trim(),taxa_entrega:Number($('#cfg-taxa').value||0),pedido_minimo:Number($('#cfg-minimo').value||0),tempo_entrega_min:Number($('#cfg-tempo-min').value||0),tempo_entrega_max:Number($('#cfg-tempo-max').value||0),aberto:$('#cfg-aberto').checked,mensagem_fechado:$('#cfg-mensagem').value.trim()};if(dados.tempo_entrega_max<dados.tempo_entrega_min)return toast('O tempo máximo deve ser maior ou igual ao mínimo.',true);try{await api('api/admin.php?recurso=configuracoes',{method:'PATCH',body:JSON.stringify(dados)});toast('Configurações salvas.')}catch(e){toast(e.message,true)}});

  const marmitasDia=await api('api/admin.php?recurso=marmitas_dia'),gridMD=$('#grid-marmitas-dia');
  const mdComps=x=>(x.marmitas_do_dia_ingredientes||[]).map(i=>i.ingredientes).filter(Boolean);
  const mdPreco=x=>x.preco_promocional==null?Number(x.tamanhos_marmita?.preco||0)+mdComps(x).reduce((a,i)=>a+Number(i.preco_adicional||0),0):Number(x.preco_promocional);
  if(gridMD)gridMD.innerHTML=marmitasDia.length?marmitasDia.map(x=>`<div class="col-xl-4 col-md-6"><div class="menu-admin-card h-100"><div class="menu-admin-image">${x.imagem_url?`<img src="${x.imagem_url}" alt="${x.nome}">`:'<i class="bi bi-calendar2-heart"></i>'}</div><div class="menu-admin-info"><div class="d-flex justify-content-between gap-2"><h3>${x.nome}</h3><span class="available">${x.publicada?'Publicada':(x.disponivel?'Salva':'Inativa')}</span></div><p>${x.tamanhos_marmita?.nome||''} • ${mdComps(x).map(i=>i.nome).join(', ')||'Sem ingredientes'}</p><strong>${money(mdPreco(x))}</strong><div class="menu-actions flex-wrap"><button class="btn-outline-custom edit-md" data-id="${x.id}"><i class="bi bi-pencil"></i> Editar</button>${x.publicada?'':`<button class="btn-cta pub-md" data-id="${x.id}"><i class="bi bi-upload"></i> Publicar</button>`}<button class="btn-outline-custom dup-md" data-id="${x.id}"><i class="bi bi-copy"></i></button><button class="delete-btn del-md" data-id="${x.id}"><i class="bi bi-trash"></i></button></div></div></div></div>`).join(''):'<div class="col-12"><p>Nenhuma marmita do dia salva. Crie a primeira.</p></div>';
  const modalMD=$('#modalMarmitaDia')?new bootstrap.Modal($('#modalMarmitaDia')):null;let mdImg='';
  const mdPreview=url=>{const w=$('#marmita-dia-preview-wrap'),im=$('#marmita-dia-preview');if(url){im.src=url;w.classList.remove('d-none')}else{im.removeAttribute('src');w.classList.add('d-none')}};
  const limites={Carboidrato:'max_carboidratos','Proteína':'max_proteinas','Acompanhamento':'max_acompanhamentos','Salada':'max_saladas'};
  const renderMDIngredientes=(sel=[])=>{const t=tamanhos.find(x=>String(x.id)===$('#marmita-dia-tamanho').value);const box=$('#marmita-dia-ingredientes');if(!box||!t)return;box.innerHTML=Object.entries(limites).map(([cat,k])=>{const max=Number(t[k]||0),lista=ings.filter(i=>i.categoria===cat&&i.disponivel);if(max<=0)return '';return `<div class="mb-3"><strong>${cat}</strong> <small class="text-muted">(até ${max})</small><div class="row g-2 mt-1">${lista.map(i=>`<div class="col-md-6 col-xl-4"><label class="md-ing-option"><input type="checkbox" class="md-ing-check" data-cat="${cat}" value="${i.id}" ${sel.map(String).includes(String(i.id))?'checked':''}> <span>${i.nome}${Number(i.preco_adicional)>0?' • +'+money(i.preco_adicional):''}</span></label></div>`).join('')||'<small>Nenhuma opção disponível.</small>'}</div></div>`}).join('');$$('.md-ing-check',box).forEach(c=>c.onchange=()=>{const max=Number(t[limites[c.dataset.cat]]||0),checked=$$(`.md-ing-check[data-cat="${c.dataset.cat}"]:checked`,box);if(checked.length>max){c.checked=false;toast(`Máximo de ${max} em ${c.dataset.cat}.`,true)}})};
  const abrirMD=(x=null,duplicar=false)=>{const base=x||{};$('#marmita-dia-id').value=duplicar?'':(base.id||'');$('#marmita-dia-nome').value=duplicar?(base.nome?base.nome+' - cópia':''):(base.nome||'');$('#marmita-dia-descricao').value=base.descricao||'';$('#marmita-dia-tamanho').innerHTML=tamanhos.filter(t=>t.disponivel||String(t.id)===String(base.tamanho_id)).map(t=>`<option value="${t.id}">${t.nome} — ${money(t.preco)}</option>`).join('');$('#marmita-dia-tamanho').value=base.tamanho_id||tamanhos[0]?.id||'';$('#marmita-dia-preco').value=base.preco_promocional??'';$('#marmita-dia-disponivel').checked=base.disponivel??true;$('#marmita-dia-publicada').checked=duplicar?false:!!base.publicada;$('#marmita-dia-imagem').value='';mdImg=base.imagem_url||'';mdPreview(mdImg);renderMDIngredientes(mdComps(base).map(i=>i.id));$('#tituloModalMarmitaDia').textContent=duplicar?'Duplicar marmita':(x?'Editar marmita do dia':'Nova marmita do dia');modalMD?.show()};
  $('#nova-marmita-dia')?.addEventListener('click',()=>abrirMD());$('#marmita-dia-tamanho')?.addEventListener('change',()=>renderMDIngredientes([]));$$('.edit-md').forEach(b=>b.onclick=()=>abrirMD(marmitasDia.find(x=>String(x.id)===b.dataset.id)));$$('.dup-md').forEach(b=>b.onclick=()=>abrirMD(marmitasDia.find(x=>String(x.id)===b.dataset.id),true));$$('.pub-md').forEach(b=>b.onclick=async()=>{try{await api('api/admin.php?recurso=marmita_dia_publicar&id='+b.dataset.id,{method:'PATCH',body:'{}'});toast('Marmita publicada na página inicial.');setTimeout(()=>location.reload(),400)}catch(e){toast(e.message,true)}});$$('.del-md').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir esta marmita do dia salva?'))return;try{await api('api/admin.php?recurso=marmita_dia&id='+b.dataset.id,{method:'DELETE'});toast('Marmita excluída.');setTimeout(()=>location.reload(),400)}catch(e){toast(e.message,true)}});
  $('#marmita-dia-imagem')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024){e.target.value='';return toast('Use JPG, PNG ou WebP de até 5 MB.',true)}mdPreview(URL.createObjectURL(f))});
  $('#formMarmitaDia')?.addEventListener('submit',async e=>{e.preventDefault();const id=$('#marmita-dia-id').value,t=tamanhos.find(x=>String(x.id)===$('#marmita-dia-tamanho').value),checks=$$('.md-ing-check:checked'),ids=checks.map(c=>Number(c.value));if(!t)return toast('Escolha um tamanho.',true);for(const [cat,k] of Object.entries(limites)){const n=checks.filter(c=>c.dataset.cat===cat).length,max=Number(t[k]||0);if(max>0&&n===0)return toast(`Escolha pelo menos um item de ${cat}.`,true);if(n>max)return toast(`Máximo de ${max} em ${cat}.`,true)}const dados={nome:$('#marmita-dia-nome').value.trim(),descricao:$('#marmita-dia-descricao').value.trim(),tamanho_id:Number(t.id),preco_promocional:$('#marmita-dia-preco').value===''?null:Number($('#marmita-dia-preco').value),disponivel:$('#marmita-dia-disponivel').checked,publicada:$('#marmita-dia-publicada').checked,ingredientes:ids,imagem_url:mdImg||null};try{const arq=$('#marmita-dia-imagem').files?.[0];if(arq){const {data:{user}}=await db.auth.getUser();if(!user)throw new Error('Sessão expirada.');const ext=(arq.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase();const path=`marmitas-do-dia/${user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('produtos').upload(path,arq,{contentType:arq.type});if(error)throw error;dados.imagem_url=db.storage.from('produtos').getPublicUrl(path).data.publicUrl}await api('api/admin.php?recurso=marmita_dia'+(id?'&id='+id:''),{method:id?'PATCH':'POST',body:JSON.stringify(dados)});toast('Marmita do dia salva.');modalMD?.hide();setTimeout(()=>location.reload(),400)}catch(e){toast(e.message,true)}});
 }catch(e){toast(e.message,true)}
}
document.addEventListener('DOMContentLoaded',async()=>{badge();ensureLoginDesign();passwordEyes();await authHeader();await home();await cadastro();await login();await montarMarmita();await carrinho();await admin()});
