<?php require_once __DIR__.'/../config.php';
if($_SERVER['REQUEST_METHOD']!=='POST')json_out(['error'=>'Método inválido'],405);if(!bearer())json_out(['error'=>'Não autenticado'],401);$b=body();$uid=$b['usuario_id']??'';$items=$b['itens']??[];if(!$uid||!$items)json_out(['error'=>'Carrinho vazio'],422);
$prof=sb('GET','usuarios?select=id,endereco&id=eq.'.q($uid).'&limit=1')['data'][0]??null;if(!$prof||!$prof['endereco'])json_out(['error'=>'Cadastre um endereço antes de pedir.'],422);
$cfg=sb('GET','configuracoes_loja?select=taxa_entrega,pedido_minimo,aberto,mensagem_fechado&limit=1')['data'][0]??[];if(isset($cfg['aberto'])&&!$cfg['aberto'])json_out(['error'=>$cfg['mensagem_fechado']??'A loja está fechada.'],422);$taxa=(float)($cfg['taxa_entrega']??0);$calc=[];$subtotal=0;
foreach($items as $it){$tid=(int)($it['tamanho_id']??0);$tam=sb('GET','tamanhos_marmita?select=*&id=eq.'.$tid.'&disponivel=eq.true&limit=1',null,false)['data'][0]??null;if(!$tam)json_out(['error'=>'Tamanho inválido'],422);$ids=array_values(array_map('intval',$it['ingrediente_ids']??[]));$ings=[];if($ids){$filter='('.implode(',',$ids).')';$ings=sb('GET','ingredientes?select=*&id=in.'.q($filter).'&disponivel=eq.true',null,false)['data'];}
 $counts=[];foreach($ings as $x)$counts[$x['categoria']]=($counts[$x['categoria']]??0)+1;$limits=['Carboidrato'=>'max_carboidratos','Proteína'=>'max_proteinas','Acompanhamento'=>'max_acompanhamentos','Salada'=>'max_saladas'];foreach($counts as $cat=>$n)if(isset($limits[$cat])&&$n>(int)$tam[$limits[$cat]])json_out(['error'=>'Quantidade de ingredientes acima do permitido.'],422);
 $unit=(float)$tam['preco'];foreach($ings as $x)$unit+=(float)$x['preco_adicional'];$nomeItem=$tam['nome'];
 $mdid=(int)($it['marmita_dia_id']??0);if($mdid){$md=sb('GET','marmitas_do_dia?select=id,nome,tamanho_id,preco_promocional,disponivel&id=eq.'.$mdid.'&disponivel=eq.true&limit=1',null,false)['data'][0]??null;if(!$md||(int)$md['tamanho_id']!==$tid)json_out(['error'=>'Marmita do dia inválida ou indisponível.'],422);$comp=sb('GET','marmitas_do_dia_ingredientes?select=ingrediente_id&marmita_dia_id=eq.'.$mdid,null,false)['data']??[];$esperados=array_values(array_map(fn($x)=>(int)$x['ingrediente_id'],$comp));sort($esperados);$recebidos=$ids;sort($recebidos);if($esperados!==$recebidos)json_out(['error'=>'A composição da marmita do dia foi alterada. Atualize o carrinho.'],422);if($md['preco_promocional']!==null)$unit=(float)$md['preco_promocional'];$nomeItem=$md['nome'];}
 $subtotal+=$unit;$calc[]=['tam'=>$tam,'ings'=>$ings,'unit'=>$unit,'nome'=>$nomeItem];}
$minimo=(float)($cfg['pedido_minimo']??0);if($subtotal<$minimo)json_out(['error'=>'Pedido mínimo: R$ '.number_format($minimo,2,',','.')],422);
$pedido=sb('POST','pedidos?select=*',['usuario_id'=>$uid,'forma_pagamento'=>'Pix','subtotal'=>$subtotal,'taxa_entrega'=>$taxa,'valor_total'=>$subtotal+$taxa,'endereco_entrega'=>$prof['endereco']],true,['Prefer: return=representation'])['data'][0]??null;if(!$pedido)json_out(['error'=>'Não foi possível criar o pedido'],500);
foreach($calc as $x){$item=sb('POST','itens_pedido?select=*',['pedido_id'=>$pedido['id'],'nome_item'=>$x['nome'],'tamanho'=>$x['tam']['nome'],'quantidade'=>1,'preco_unitario'=>$x['unit'],'subtotal'=>$x['unit']],true,['Prefer: return=representation'])['data'][0]??null;if($item&&$x['ings']){$rows=[];foreach($x['ings'] as $y)$rows[]=['item_pedido_id'=>$item['id'],'ingrediente_id'=>$y['id'],'nome_ingrediente'=>$y['nome'],'categoria'=>$y['categoria'],'quantidade'=>1,'preco_adicional'=>(float)$y['preco_adicional']];sb('POST','itens_pedido_ingredientes',$rows,true,['Prefer: return=minimal']);}}
json_out(['pedido'=>$pedido]);
